port: 7890
socks-port: 7891
mixed-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
experimental:
  ignore-resolve-fail: true

dns:
  enable: true
  # ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    #- 223.6.6.6
  nameserver:
    #如果你有自建的DNS服务器或专用网络的DNS服务器可在托管链接添加如 &dns=9.9.9.9 参数
    #自定义DNS将添加在下方并优先使用 支持Doh/Dot等dns
    #注意: 9.9.9.9替换成你要自定义的DNS，此DNS必须有效，否则将导致出错无法使用

    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    #- https://doh.pub/dns-query
    #- https://dns.alidns.com/dns-query
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"

# Clash for Windows
cfw-latency-timeout: 3000
cfw-latency-url: http://cp.cloudflare.com/generate_204
cfw-conn-break-strategy: true

# Clash for Android
clash-for-android:
  ui-subtitle-pattern: '[\u4e00-\u9fa5]{2,4}'

# Stash
url-rewrite:
  - ^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
  - ^https?:\/\/(ditu|maps).google\.cn https://maps.google.com 302

proxies:
  - name: "My SS Proxy 1"
    type: ss
    server: 188.166.213.47
    port: 29093
    cipher: chacha20-ietf-poly1305
    password: "XBgTYyGE0wMEylXsjcf9dn"
    udp: true
    plugin: ""
    plugin-opts: {}

  - name: "My SS Proxy 2"
    type: ss
    server: 143.110.166.28
    port: 10818
    cipher: chacha20-ietf-poly1305
    password: "NJcWAWTEWFOB9de5jtsG5m"
    udp: true
    plugin: ""
    plugin-opts: {}

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "My SS Proxy 1"
      - "My SS Proxy 2"

rule-providers:
  Global:
    type: http
    behavior: classical
    path: ./Rules/Global.yaml
    url: https://cdn.gitmirror.com/gh/tututo/Profiles@master/Clash/RuleSet/Global.yaml
    interval: 86400
  China:
    type: http
    behavior: classical
    path: ./Rules/China.yaml
    url: https://cdn.gitmirror.com/gh/tututo/Profiles@master/Clash/RuleSet/China.yaml
    interval: 86400
  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./Rules/ChinaIP.yaml
    url: https://cdn.gitmirror.com/gh/tututo/Profiles@master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400

rules:
  - RULE-SET,Global,Proxy
  - RULE-SET,China,DIRECT
  - RULE-SET,ChinaIP,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT

  - GEOIP,CN,DIRECT

  - MATCH,Proxy
