allow-lan: true
cfw-conn-break-strategy: true
cfw-latency-timeout: 3000
cfw-latency-url: http://cp.cloudflare.com/generate_204
clash-for-android:
  ui-subtitle-pattern: '[\u4e00-\u9fa5]{2,4}'
dns:
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - '*.localdomain'
  - '*.example'
  - '*.invalid'
  - '*.localhost'
  - '*.test'
  - '*.local'
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:53
  nameserver:
  - https://223.5.5.5/dns-query
  - https://1.12.12.12/dns-query
experimental:
  ignore-resolve-fail: true
external-controller: 0.0.0.0:9090
log-level: info
mixed-port: 7892
mode: Rule
port: 7890
proxies:
- cipher: chacha20-ietf-poly1305
  name: My SS Proxy 1
  password: XBgTYyGE0wMEylXsjcf9dn
  plugin: ''
  plugin-opts: {}
  port: 29093
  server: 188.166.213.47
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: My SS Proxy 2
  password: NJcWAWTEWFOB9de5jtsG5m
  plugin: ''
  plugin-opts: {}
  port: 10818
  server: 143.110.166.28
  type: ss
  udp: true
proxy-groups:
- name: Proxy
  proxies:
  - My SS Proxy 1
  - My SS Proxy 2
  type: select
rule-providers:
  China:
    behavior: classical
    interval: 86400
    path: ./Rules/China.yaml
    type: http
    url: https://cdn.gitmirror.com/gh/tututo/Profiles@master/Clash/RuleSet/China.yaml
  ChinaIP:
    behavior: ipcidr
    interval: 86400
    path: ./Rules/ChinaIP.yaml
    type: http
    url: https://cdn.gitmirror.com/gh/tututo/Profiles@master/Clash/RuleSet/Extra/ChinaIP.yaml
  Global:
    behavior: classical
    interval: 86400
    path: ./Rules/Global.yaml
    type: http
    url: https://cdn.gitmirror.com/gh/tututo/Profiles@master/Clash/RuleSet/Global.yaml
rules:
- RULE-SET,Global,Proxy
- RULE-SET,China,DIRECT
- RULE-SET,ChinaIP,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- IP-CIDR,224.0.0.0/4,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Proxy
socks-port: 7891
url-rewrite:
- ^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
- ^https?:\/\/(ditu|maps).google\.cn https://maps.google.com 302
